import { CommercialFertilizer } from '../types';

export const CATALOGO_FERTILIZANTES: CommercialFertilizer[] = [
  // --- MATÉRIAS-PRIMAS NITROGENADAS ---
  {
    id: 'ureia',
    nome: 'Ureia Agrícola (45% N)',
    tipo: 'simples',
    teorN: 45,
    teorP2O5: 0,
    teorK2O: 0,
    precoSaco50kg: 165.0,
    unidade: 'saco50kg',
    descricao: 'Fonte mais concentrada de N. Alto índice salino; aplicar em solo úmido ou incorporar.',
  },
  {
    id: 'sulfato_amonio',
    nome: 'Sulfato de Amônio (21% N + 24% S)',
    tipo: 'simples',
    teorN: 21,
    teorP2O5: 0,
    teorK2O: 0,
    teorS: 24,
    precoSaco50kg: 125.0,
    unidade: 'saco50kg',
    descricao: 'Excelente para suprir Enxofre (S) essencial na síntese de aminoácidos e aroma do café.',
  },
  {
    id: 'nitrato_amonio',
    nome: 'Nitrato de Amônio (33% N)',
    tipo: 'simples',
    teorN: 33,
    teorP2O5: 0,
    teorK2O: 0,
    precoSaco50kg: 175.0,
    unidade: 'saco50kg',
    descricao: 'Absorção mais rápida, menor risco de perdas por volatilização que a ureia.',
  },

  // --- MATÉRIAS-PRIMAS FOSFATADAS ---
  {
    id: 'map',
    nome: 'MAP - Fosfato Monoamônico (11% N + 52% P2O5)',
    tipo: 'simples',
    teorN: 11,
    teorP2O5: 52,
    teorK2O: 0,
    precoSaco50kg: 240.0,
    unidade: 'saco50kg',
    descricao: 'Fósforo altamente solúvel e concentrado, com arranque nitrogenado.',
  },
  {
    id: 'super_simples',
    nome: 'Superfosfato Simples (18% P2O5 + 10% S + 18% Ca)',
    tipo: 'simples',
    teorN: 0,
    teorP2O5: 18,
    teorK2O: 0,
    teorS: 10,
    teorCa: 18,
    precoSaco50kg: 110.0,
    unidade: 'saco50kg',
    descricao: 'Aporte simultâneo de P, Cálcio e Enxofre, muito valorizado para o sistema radicular.',
  },
  {
    id: 'super_triplo',
    nome: 'Superfosfato Triplo (41% P2O5 + 10% Ca)',
    tipo: 'simples',
    teorN: 0,
    teorP2O5: 41,
    teorK2O: 0,
    teorCa: 10,
    precoSaco50kg: 210.0,
    unidade: 'saco50kg',
    descricao: 'Alta concentração de P2O5, reduz frete e volume de aplicação.',
  },

  // --- MATÉRIAS-PRIMAS POTÁSSICAS ---
  {
    id: 'kcl',
    nome: 'Cloreto de Potássio - KCl (60% K2O)',
    tipo: 'simples',
    teorN: 0,
    teorP2O5: 0,
    teorK2O: 60,
    precoSaco50kg: 195.0,
    unidade: 'saco50kg',
    descricao: 'Fonte de K mais econômica do mercado. Fundamental no enchimento de frutos e brix.',
  },
  {
    id: 'sulfato_potassio',
    nome: 'Sulfato de Potássio (50% K2O + 17% S)',
    tipo: 'simples',
    teorN: 0,
    teorP2O5: 0,
    teorK2O: 50,
    teorS: 17,
    precoSaco50kg: 260.0,
    unidade: 'saco50kg',
    descricao: 'Baixo índice salino e isento de cloro. Muito utilizado em cafés especiais e solos salinos.',
  },

  // --- FÓRMULAS NPK INDUSTRIAIS DE COBERTURA ---
  {
    id: 'npk_20_00_20',
    nome: 'NPK 20-00-20 (Mistura de Grânulos)',
    tipo: 'formulado',
    teorN: 20,
    teorP2O5: 0,
    teorK2O: 20,
    precoSaco50kg: 155.0,
    unidade: 'saco50kg',
    descricao: 'Fórmula clássica de cobertura para cafeeiros adultos quando o fósforo no solo está alto.',
  },
  {
    id: 'npk_20_05_20',
    nome: 'NPK 20-05-20',
    tipo: 'formulado',
    teorN: 20,
    teorP2O5: 5,
    teorK2O: 20,
    precoSaco50kg: 168.0,
    unidade: 'saco50kg',
    descricao: 'Equilíbrio ideal de manutenção com pequena dose de P2O5 para reposição de colheita.',
  },
  {
    id: 'npk_19_04_19',
    nome: 'NPK 19-04-19 + Micronutrientes',
    tipo: 'formulado',
    teorN: 19,
    teorP2O5: 4,
    teorK2O: 19,
    teorB: 0.2,
    teorZn: 0.3,
    precoSaco50kg: 178.0,
    unidade: 'saco50kg',
    descricao: 'Fórmula enriquecida com Boro e Zinco para florada e pegamento de frutos.',
  },

  // --- MICRONUTRIENTES E CORRETIVOS ---
  {
    id: 'acido_borico',
    nome: 'Ácido Bórico / Octaborato (17% B)',
    tipo: 'simples',
    teorN: 0,
    teorP2O5: 0,
    teorK2O: 0,
    teorB: 17,
    precoSaco50kg: 320.0,
    unidade: 'saco50kg',
    descricao: 'Essencial para brotação de raízes novas e fertilização floral (evita abortamento).',
  },
  {
    id: 'sulfato_zinco',
    nome: 'Sulfato de Zinco (21% Zn + 10% S)',
    tipo: 'simples',
    teorN: 0,
    teorP2O5: 0,
    teorK2O: 0,
    teorZn: 21,
    teorS: 10,
    precoSaco50kg: 210.0,
    unidade: 'saco50kg',
    descricao: 'Evita enfezamento e folhas pequeninas (rosetamento) do cafeeiro.',
  },
  {
    id: 'gesso_agricola',
    nome: 'Gesso Agrícola (Sulfato de Cálcio - 16% S, 18% Ca)',
    tipo: 'simples',
    teorN: 0,
    teorP2O5: 0,
    teorK2O: 0,
    teorS: 16,
    teorCa: 18,
    precoSaco50kg: 28.0,
    unidade: 'tonelada',
    descricao: 'Condicionador de subsuperfície (20-40cm). Carrega Ca em profundidade e neutraliza Al.',
  },
  {
    id: 'calcario_dolomitico',
    nome: 'Calcário Dolomítico (PRNT 85%, MgO > 15%)',
    tipo: 'simples',
    teorN: 0,
    teorP2O5: 0,
    teorK2O: 0,
    teorCa: 32,
    teorMg: 18,
    precoSaco50kg: 220.0,
    unidade: 'tonelada',
    descricao: 'Corrige acidez do solo e eleva teores de Magnésio, centro da molécula de clorofila.',
  },
  {
    id: 'palha_cafe',
    nome: 'Palha de Café Residual (Reciclagem Orgânica)',
    tipo: 'organico',
    teorN: 1.5,
    teorP2O5: 0.3,
    teorK2O: 2.6,
    precoSaco50kg: 0.0,
    unidade: 'tonelada',
    descricao: 'Resíduo do benefício próprio da fazenda. Rico em K2O orgânico e retentor hídrico.',
  }
];
